pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - author=dependabot[bot]
  - check-success*=ci/hydra:ppd-rs:*:aarch64-linux.hydra-spec
  - check-success*=ci/hydra:ppd-rs:*:aarch64-linux.mergify-check
  - check-success*=ci/hydra:ppd-rs:*:aarch64-linux.ppd
  - check-success*=ci/hydra:ppd-rs:*:aarch64-linux.ppd-clippy
  - check-success*=ci/hydra:ppd-rs:*:aarch64-linux.ppd-deny
  - check-success*=ci/hydra:ppd-rs:*:aarch64-linux.ppd-fmt
  - check-success*=ci/hydra:ppd-rs:*:aarch64-linux.pre-commit-check
  - check-success*=ci/hydra:ppd-rs:*:aarch64-linux.vm-test
  - check-success*=ci/hydra:ppd-rs:*:x86_64-linux.hydra-spec
  - check-success*=ci/hydra:ppd-rs:*:x86_64-linux.mergify-check
  - check-success*=ci/hydra:ppd-rs:*:x86_64-linux.ppd
  - check-success*=ci/hydra:ppd-rs:*:x86_64-linux.ppd-clippy
  - check-success*=ci/hydra:ppd-rs:*:x86_64-linux.ppd-deny
  - check-success*=ci/hydra:ppd-rs:*:x86_64-linux.ppd-fmt
  - check-success*=ci/hydra:ppd-rs:*:x86_64-linux.pre-commit-check
  - check-success*=ci/hydra:ppd-rs:*:x86_64-linux.vm-test
  name: Automatically merge dependabot updates
